### ISSUE TITLE
"rsa_ecb_encrypt/rsa_ecb_decrypt" replace "rsa_encrypt/rsa_decrypt"? 

### ISSUE THREAD

**Issue by flylink888** [alimtolman/cryptopp-helper-delphi#1]
This package is very good, so that Delphi developers are blessed!

After compiling and using it yesterday, I found that there is no "rsa_encrypt / rsa_decrypt". I guess it may be replaced by "rsa_ecb_encrypt / rsa_ecb_decrypt". I want to verify it! thank you!

**Comment by alimtolman** [comment]
You're right. Updated it.
